name: ec2-update
run-name: ${{ github.actor }} is deploying an EC2 instance!
on: workflow_dispatch
jobs:
  ec2-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      # - run: ls
      # - run: pwd
      # - run: cd ..
      # - run: ls
      - name: Zip all files so that we can upload it to EC2, later on we can ignore certain files
        run: zip all_files *
      - name: Deploy to EC2 using AWS-CLI