name: ec2-deploy
run-name: ${{ github.actor }} is deploying an EC2 instance!
# Trigger deployment only on push on main
on:
  push:
    branches:
      - "main"
jobs:
  create_ec2_instance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Create EC2 instance
        run: |
          aws ec2 run-instances --image-id ami-0c94855ba95c71c99 --instance-type t2.micro --key-name ${{ secrets.EC2_KEY_PAIR }} --security-group-ids sg-xxxxx --subnet-id subnet-xxxxxx
      
    
     